AmazonBookstore/Components/TypesViewComponent.cs
using AmazonBookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AmazonBookstore.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IAmazonBookstoreRepository repo { get; set; }

        public TypesViewComponent(IAmazonBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["Category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

AmazonBookstore/Views/Shared/BookSummary.cshtml
@{
}

@model Book
 
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title

        </h4>
    </div>
    <div class="card-text p-1">Author: @Model.Author</div>
    <div class="card-text p-1">Publisher: @Model.Publisher</div>
    <div class="card-text p-1">ISBN: @Model.Isbn </div>
    <div class="card-text p-1">Classification: @Model.Classification</div>
    <div class="card-text p-1">Category: @Model.Category</div>
    <div class="card-text p-1">Page Count: @Model.PageCount</div>
    <div class="card-text p-1">Price: $@Model.Price</div>

    <form method="post" asp-page="/AddToCart">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>

    </form>

</div>

AmazonBookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AmazonBookstore</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/css/bootstrap.css" rel="stylesheet" />

</head>
<body>
    @*Changed color of header*@
    <div class="bg-info text-dark p-3">
        <span class="navbar-brand m-lg-2">AMAZON BOOKSTORE</span>
        <vc:cart-summary />
    </div>

    @*<div class="col-6 text-right">

        </div>*@

    <div class="row m-1 p-1">

        <div id="types" class="col-3">
            <vc:types></vc:types>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>

        </div>

    </div>




</body>
<footer class="border-top footer text-muted">
    <div class="container">
        2022 - Amazon Bookstore - Joseph Espiritu IS413 
    </div>
</footer>
</html>